#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
services:
  hasher:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: secobau/dockercoins-hasher:release-1.1
  redis:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: redis
  rng:
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
      restart_policy:
        condition: any
    image: secobau/dockercoins-rng:release-1.1
  webui:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: secobau/dockercoins-webui:release-1.1
    ports:
    - "31001:80"
  worker:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: secobau/dockercoins-worker:release-1.1
version: "3.8"
#########################################################################
