#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
services:
  php:
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      restart_policy:
        condition: any
    image: secobau/php:rc-apache-1.1
    ports:
    - "30001:80"
version: "3.8"
#########################################################################
